alias: PV clipping - make room in battery at sunrise
description: >-
  Make room in battery at sunrise if PV clipping is forecast in the next 24
  hours
trigger:
  - platform: state
    entity_id:
      - input_number.pv_clipped_in_next_24_hours
condition:
  - condition: numeric_state
    entity_id: predbat.rates
    above: 0
  - condition: template
    value_template: |
      {{ states('input_number.pv_clipped_in_next_24_hours') | float > 0 }}
action:
  - service: select.select_option
    metadata: {}
    data:
      option: >
        {# Round down the time to nearest half-hour #}   {% set t =
        utcnow().strftime("%s") | int %}   {{ (t - (t % 1800) + 9000) |
        timestamp_custom("%H:%M:%S") }}
    target:
      entity_id: select.predbat_manual_discharge
  - if:
      - condition: template
        value_template: >-
          {#  Default is 1.8 kWh in 30 minutes. Change to your battery output
          rate. #}    

          {% set battery_max_output = namespace(value = 1.8) %}    

          {{ states('input_number.pv_clipped_in_next_24_hours') >
          battery_max_output }}
    then:
      - service: select.select_option
        metadata: {}
        data:
          option: >
            {# Round up the time to nearest half-hour #}   {% set t =
            utcnow().strftime("%s") | int %}   {{ (t - (t % 1800) + 7200) |
            timestamp_custom("%H:%M:%S") }}
        target:
          entity_id: select.predbat_manual_discharge
  - if:
      - condition: template
        value_template: >-
          {#  Default is 1.8 kWh in 30 minutes. Change to your battery output
          rate. #}    

          {% set battery_max_output = namespace(value = 1.8) %}    

          {{ states('input_number.pv_clipped_in_next_24_hours') >
          (battery_max_output * 2) }}
    then:
      - service: select.select_option
        metadata: {}
        data:
          option: >
            {% set t = utcnow().strftime("%s") | int %}    {{ (t - (t % 1800) +
            5400) | timestamp_custom("%H:%M:%S") }}
        target:
          entity_id: select.predbat_manual_discharge
  - if:
      - condition: template
        value_template: >-
          {#  Default is 1.8 kWh in 30 minutes. Change to your battery output
          rate. #}    

          {% set battery_max_output = namespace(value = 1.8) %}    

          {{ states('input_number.pv_clipped_in_next_24_hours') >
          (battery_max_output * 3) }}
    then:
      - service: select.select_option
        metadata: {}
        data:
          option: >
            {% set t = utcnow().strftime("%s") | int %}    {{ (t - (t % 1800) +
            3600) | timestamp_custom("%H:%M:%S") }}
        target:
          entity_id: select.predbat_manual_discharge
  - if:
      - condition: template
        value_template: >-
          {#  Default is 1.8 kWh in 30 minutes. Change to your battery output
          rate. #}    

          {% set battery_max_output = namespace(value = 1.8) %}    

          {{ states('input_number.pv_clipped_in_next_24_hours') >
          (battery_max_output * 4) }}
    then:
      - service: select.select_option
        metadata: {}
        data:
          option: >
            {% set t = utcnow().strftime("%s") | int %}    {{ (t - (t % 1800) +
            1800) | timestamp_custom("%H:%M:%S") }}
        target:
          entity_id: select.predbat_manual_discharge
  - if:
      - condition: template
        value_template: >-
          {#  Default is 1.8 kWh in 30 minutes. Change to your battery output
          rate. #}    

          {% set battery_max_output = namespace(value = 1.8) %}    

          {{ states('input_number.pv_clipped_in_next_24_hours') >
          (battery_max_output * 5) }}
    then:
      - service: select.select_option
        metadata: {}
        data:
          option: >
            {% set t = utcnow().strftime("%s") | int %}    {{ (t - (t % 1800)) |
            timestamp_custom("%H:%M:%S") }}
        target:
          entity_id: select.predbat_manual_discharge
mode: single
