alias: PV clipping - make room in battery overnight
description: >-
  Don't allow predbat to fill battery overnight if PV clipping is forecast in
  the next 24 hours
trigger:
  - platform: time
    at: "00:05:00"
condition: []
action:
  - service: input_number.set_value
    metadata: {}
    data:
      value: >
        {# Default is 5 kW hybrid inverter.  Change the 5 to 3.6 if you have a 3.6 kW inverter#}  
        {% set inverter_limit = namespace(value = 5 / 6) %} 
        {# Default is 9.5 kW battery. Change to your battery capacity. #}  
        {% set battery_max_capacity = namespace(value = 9.5) %}  
        {% set pv_clipped = namespace(value=0.0) %}  
        {% set pv_prev = namespace(value=0.0) %}  
        {% set pv_cur = namespace(value=0.0) %}  
        {%- for this_item in state_attr('predbat.pv_energy', 'results') -%}
          {% if loop.index0 == 0 %}
            {%- set pv_prev.value = state_attr('predbat.pv_energy', 'results')[this_item] | float -%}
          {% else %}
            {%- set pv_cur.value = state_attr('predbat.pv_energy', 'results')[this_item] | float -%}
            {% if pv_cur.value - pv_prev.value > inverter_limit.value %}
              {%- set pv_clipped.value = pv_clipped.value + pv_cur.value - pv_prev.value - inverter_limit.value -%}
            {% endif %}
            {%- set pv_prev.value = pv_cur.value -%}
          {% endif %}
          {# Only look at the next 24 hours (each loop is 10 minutes) #}
          {% if loop.index0 == 144 %}
            {% break %}
          {% endif %}
        {%- endfor -%}  
        {{ (battery_max_capacity.value - pv_clipped.value) | float }}
    target:
      entity_id: input_number.predbat_best_soc_max
mode: single
