alias: PV clipping - Set best_soc_max to 0 auto
description: At sunset, reset best_soc_max input variable
trigger:
  - platform: sun
    event: sunset
    offset: 0
condition: []
action:
  - service: input_number.set_value
    metadata: {}
    data:
      value: 0
    target:
      entity_id: input_number.predbat_best_soc_max
mode: single
