alias: PV clipping - PV drops below inverter limit
description: >-
  Predbat force manual discharge to prioritise export over battery charging if
  the sun goes behind a cloud. (Replace geserial with your GE inverter serial
  number. Replace 5000 with your hybrid inverter limit in Watts.)
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.givtcp_fd2249g771_pv_power
    below: 5000
condition:
  - condition: numeric_state
    entity_id: predbat.rates
    above: 0
  - condition: template
    value_template: |-
      {# Check this half-hour is not already set to force discharge #} 
      {% set t =  utcnow().strftime("%s") | int %} 
      {% set half_hour = (t - (t % 1800 )) | timestamp_custom("%H:%M:%S") %}
      {{ half_hour not in states('select.predbat_manual_discharge') }}
action:
  - service: select.select_option
    metadata: {}
    data:
      option: >
        {# Round down the time to nearest half-hour #}  {% set t = 
        utcnow().strftime("%s") | int %}  {{ (t - (t % 1800 )) |
        timestamp_custom("%H:%M:%S") }}
    target:
      entity_id: select.predbat_manual_discharge
mode: single
